- name: Install and update docker pre-requisites
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: yes

- name: Add docker gpg apt key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_version_codename }} stable
    state: present

- name: Update apt and install docker community edition
  become: true
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true
