all:
  children:
    ansible_hosts_first_time_setup:
      hosts:
        dl20-server:
      vars:
        ansible_become_password: "{{ personal_account_password }}"
    ansible_hosts:
      hosts:
        dl20-server:
    ubuntu_22_04_hosts:
      hosts:
        dl20-server:
    vm_hosts:
      hosts:
        dl20-server:
    vms:
      children:
        dl20_server_vms:
          hosts:
            jumpbox:
          vars:
            vm_host: dl20-server
    docker_hosts:
      hosts:
        dl20-server:
    webserver_hosts:
      hosts:
        dl20-server:

