all:
  children:
    ansible_hosts:
      hosts:
        dl20-server:
          ansible_host: 192.168.1.36
    ubuntu_22_04_hosts:
      hosts:
        dl20-server:
    vm_hosts:
      hosts:
        dl20-server:
    vms:
      children:
        dl20-server-vms:
          hosts:
            jumpbox:
          vars:
            vm_host: dl20-server
    docker_hosts:
      hosts:
        dl20-server:
    webserver_hosts:
      hosts:
        dl20-server:

