all:
  children:
    # Ansible Hosts
    ansible_hosts:
      children:
        primary_ansible_host:
          children:
            primary_ansible_host_initial_setup:
              hosts:
                dl20-server:
              vars:
                ansible_become_password: "{{ personal_account_password }}"  # Uses personal account for first setup
    # Ubuntu Hosts
    ubuntu_22_04_hosts:
      hosts:
        dl20-server:
    # VM Hosts
    vm_hosts:
      hosts:
        dl20-server:
    # Hosted VMs
    vms:
      children:
        dl20_server_vms:
          hosts:
            jumpbox:
          vars:
            vm_host_hostname: dl20-server
    # Podman Hosts
    podman_hosts:
      hosts:
        dl20-server:
    # Caddyfile Hosts
    caddyfile_hosts:
      hosts:
        dl20-server:
    # Webserver Hosts
    webserver_hosts:
      children:
        cockpit_hosts:
          hosts:
            dl20-server:

