- name: Add ansible group
  become: true
  ansible.builtin.group:
    name: "{{ ansible_group }}"
    state: present

- name: Add ansible user account
  become: true
  ansible.builtin.user:
    name: ansible
    append: true
    groups: "sudo, {{ ansible_group }}"
    createhome: true
    state: present

- name: Add personal account to ansible group
  become: true
  ansible.builtin.user:
    name: "{{ personal_account_username }}"
    append: true
    groups: "{{ ansible_group }}"

- name: Reset ssh connection to allow account to get group changes
  ansible.builtin.meta: reset_connection

- name: Allow ansible account to have passwordless sudo
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers.d/10-ansible"
    create: true
    state: present
    regexp: '^%ansible'
    line: '%ansible ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Make sure .ssh directory exists
  become: true
  ansible.builtin.file:
    path: "{{ ansible_ssh_directory }}"
    state: directory
    owner: ansible
    group: ansible
    mode: 0700

- name: Deploy keyfiles for ansible account
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_ssh_directory }}"
    decrypt: yes
    owner: ansible
    group: ansible
    mode: 0600
    backup: no
  with_fileglob: "id_ed25519*"

- name: Get contents of ansible ssh public key file
  become: true
  ansible.builtin.slurp:
    src: "{{ ansible_ssh_directory }}/id_ed25519.pub"
  register: public_key

- name: Set up authorized keys for localhost ssh with ansible account
  become: true
  ansible.posix.authorized_key:
    user: ansible
    key: "{{ public_key['content'] | b64decode }}"

- name: Delete the ansible repo directory if is exists
  become: true
  ansible.builtin.file:
    path: "{{ ansible_repo_directory }}"
    state: absent

- name: Create the ansible repo directory
  become: true
  ansible.builtin.file:
    path: "{{ ansible_repo_directory }}"
    state: directory
    owner: ansible
    group: "{{ ansible_group }}"
    mode: 0770

- name: Clone the ansible repo
  ansible.builtin.git:
    repo: "{{ ansible_git_repo }}"
    dest: "{{ ansible_repo_directory }}"
    version: "{{ ansible_repo_branch }}"
    key_file: "/{{ ansible_user_id }}/.ssh/id_ed25519"
    accept_newhostkey: true
    clone: true
    depth: 1

- name: Create ansible virtual environment
  ansible.builtin.pip:
    requirements: "{{ ansible_repo_directory }}/requirements.txt"
    virtualenv: "{{ ansible_venv_directory }}"
    executable: pip3